import { useOsa, type ViewId } from "../ctx";
import type { Mission, TeamGraph, Run } from "../data/types";
import { useEffect, useState } from 'react';
import { requestJson } from '../data/data';
import { Mono } from '../ui/primitives';
interface Check { stage:string;status:string;detail:string;latency_ms:number;evidence_refs:{evidence_id:string;evidence_sha256:string}[] }
interface Artifact {name:string;content:string;sha256:string;bytes:number;media_type:string}
interface Result {
 report:{execution_mode:string|null;mission_id:string;state:string;verdict:string;ready_for_review:boolean;checks:Check[];coverage:{capability:string;status:string;detail:string}[];proof_id:string|null;mission_receipt:unknown;artifact:Artifact|null;limitations:string[]};
 record:{team:TeamGraph;mission:Mission;timeline:{event_type:string;timestamp:string;evidence:string[]}[]};run:Run;
}
interface Template {roles:{agent_id:string;role:string}[];modes:{starter:string;connected:string};sandbox:string;azure:string;verification_scope:string;persistence:string}
function download(name:string,content:string,type='application/json') {const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const color=(status:string)=>status==='PASS'?'text-ok':status==='FAIL'?'text-bad':status==='BLOCKED'?'text-warn':'text-dim';
export default function DeliveryLab() {
 const {inspectExecution,go,setRunId}=useOsa();
 const inspect=(view:ViewId)=>{if(result){inspectExecution(result.record.team,result.record.mission,result.run);go(view,{runId:result.run.run_id});}};
 const [template,setTemplate]=useState<Template|null>(null),[result,setResult]=useState<Result|null>(null),[error,setError]=useState(''),[running,setRunning]=useState(false);
 const [objective,setObjective]=useState('Zbuduj aplikację do zarządzania zadaniami'),[kind,setKind]=useState('webapp'),[mode,setMode]=useState('starter'),[target,setTarget]=useState('artifact'),[preview,setPreview]=useState(false);
 useEffect(()=>{requestJson<Template>('/templates/delivery-lab').then(setTemplate).catch(e=>setError(e.message));},[]);
 const run=async()=>{setRunning(true);setError('');setResult(null);setPreview(false);try{const next=await requestJson<Result>('/templates/delivery-lab/runs',{method:'POST',body:JSON.stringify({objective,kind,mode,target})});setResult(next);inspectExecution(next.record.team,next.record.mission,next.run);setRunId(next.run.run_id);}catch(e){setError(e instanceof Error?e.message:'Run failed.');}finally{setRunning(false);}};
 const report=result?.report,artifact=report?.artifact;
 return <div className="mx-auto max-w-6xl space-y-7 p-4 md:p-8">
  <header><div className="label mb-3">One team · ten roles · existing OSA runtime</div><h1 className="font-display text-2xl text-hero md:text-3xl">Delivery Lab</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-dim">Input → NeurOSA → plan → team → artifact → checks → delivery → proof. Run one bounded mission and see what worked, what failed and what remains unknown.</p></header>
  <form onSubmit={e=>{e.preventDefault();void run();}} className="space-y-4 border-y border-line py-5">
   <label className="block text-sm text-dim">Your objective<textarea required maxLength={4000} rows={3} value={objective} onChange={e=>setObjective(e.target.value)} className="focus-ring mt-2 block w-full rounded border border-line2 bg-panel p-3 text-fg"/></label>
   <div className="flex flex-wrap items-end gap-4">
    <label className="text-xs text-dim">Output<select aria-label="Output" value={kind} onChange={e=>setKind(e.target.value)} className="mt-1 block rounded border border-line2 bg-panel p-2 text-sm text-fg"><option value="webapp">Standalone webapp HTML</option><option value="document">Markdown document</option><option value="other">Other task · probe the gap</option></select></label>
    <label className="text-xs text-dim">Execution<select aria-label="Execution" value={mode} onChange={e=>setMode(e.target.value)} className="mt-1 block rounded border border-line2 bg-panel p-2 text-sm text-fg"><option value="starter">Deterministic starter</option><option value="connected">Existing model executors</option></select></label>
    <label className="text-xs text-dim">Required delivery<select aria-label="Required delivery" value={target} onChange={e=>setTarget(e.target.value)} className="mt-1 block rounded border border-line2 bg-panel p-2 text-sm text-fg"><option value="artifact">Downloadable artifact</option><option value="sandbox">Artifact + remote sandbox build/test</option><option value="azure">Azure + live verification</option></select></label>
    <button disabled={running||!template||!objective.trim()} className="focus-ring rounded border border-brand bg-brand px-5 py-2 text-sm text-onbrand disabled:opacity-50">{running?'Running mission…':'Run team'}</button>
   </div>
   <p className="text-xs leading-5 text-dim">{mode==='starter'?'Starter creates a real document scaffold or working task-list app. It does not interpret arbitrary requirements.':'Connected mode uses existing provider planner/builder. A fixture never substitutes for a model.'} Delivery passes mean bytes and declared gates are verified; human acceptance is still required.</p>
  </form>
  {error&&<p role="alert" className="text-sm text-bad">{error}</p>}
  {running&&<p role="status" className="text-sm text-dim">The server is executing the team. Per-agent live streaming is not implemented; the authoritative timeline appears with the result.</p>}
  {template&&<section><h2 className="label mb-3">Team template · v0.1.0</h2><div className="grid grid-cols-2 gap-x-5 md:grid-cols-5">{template.roles.map((agent,i)=><div key={agent.agent_id} className="border-b border-line py-3"><Mono className="text-xs text-brand">{String(i+1).padStart(2,'0')} · {agent.agent_id}</Mono><p className="mt-1 text-xs text-dim">{agent.role}</p></div>)}</div><div className="mt-4 space-y-1 text-xs text-dim"><p>Model: {template.modes.connected}</p><p>Sandbox: {template.sandbox}</p><p>Azure: {template.azure}</p><p>Storage: {template.persistence}</p></div></section>}
  {report&&<>
   <section className="border-y border-line py-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className={`text-lg ${report.ready_for_review?'text-ok':'text-warn'}`}>{report.ready_for_review?'Artifact ready for review':'Required delivery blocked or failed'}</h2><p className="mt-1 text-xs text-dim">Mission {report.state} · proof verdict {report.verdict}</p><Mono className="mt-2 block break-all text-xs">{report.mission_id}</Mono></div><div className="flex flex-wrap gap-2">{artifact&&<button className="focus-ring rounded border border-line2 px-3 py-2 text-xs" onClick={()=>download(artifact.name,artifact.content,artifact.media_type)}>Download artifact{report.ready_for_review?'':' · incomplete'}</button>}<button className="focus-ring rounded border border-line2 px-3 py-2 text-xs" onClick={()=>download(`${report.mission_id}-proof.json`,JSON.stringify(result,null,2))}>Download proof bundle</button></div></div><p className="mt-3 break-all text-xs text-dim">Proof: {report.proof_id??'Unavailable'} · MissionReceipt: {report.mission_receipt?'Present':'Absent'}</p></section>
   <div className="flex flex-wrap gap-2">{([['proofs','Verify in OSA Proof'],['trace','Open runtime trace'],['world','Open runtime world']] as const).map(([view,label])=><button key={view} className="focus-ring rounded border border-line2 px-3 py-2 text-xs" onClick={()=>inspect(view)}>{label}</button>)}</div>
   <section><h2 className="label mb-3">Execution checks · evidence from the actual run</h2><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-b border-line text-dim"><tr><th className="p-2">Agent / gate</th><th className="p-2">Result</th><th className="p-2">What was checked</th><th className="p-2">ms</th></tr></thead><tbody>{report.checks.map(check=><tr key={check.stage} className="border-b border-line align-top"><td className="p-2 font-mono">{check.stage}</td><td className={`p-2 ${color(check.status)}`}>{check.status}</td><td className="min-w-[230px] p-2 leading-5">{check.detail}<details className="mt-1 text-dim"><summary>Evidence references ({check.evidence_refs.length})</summary>{check.evidence_refs.map(e=><p key={e.evidence_id} className="max-w-xl break-all font-mono">{e.evidence_id}<br/>{e.evidence_sha256}</p>)}</details></td><td className="p-2 font-mono">{check.latency_ms}</td></tr>)}</tbody></table></div></section>
   <section><h2 className="label mb-3">Framework coverage & gaps</h2>{report.coverage.map(row=><div key={row.capability} className="grid grid-cols-[110px_70px_1fr] gap-2 border-b border-line py-3 text-xs"><span>{row.capability}</span><span className={color(row.status)}>{row.status}</span><span className="text-dim">{row.detail}</span></div>)}</section>
   {artifact&&<section><h2 className="label mb-3">Delivered bytes · {artifact.bytes} bytes</h2><Mono className="mb-3 block break-all text-xs text-dim">SHA256 {artifact.sha256}</Mono>{artifact.name.endsWith('.html')?<><button className="focus-ring mb-3 rounded border border-line2 px-3 py-2 text-xs" onClick={()=>setPreview(!preview)}>{preview?'Close isolated preview':'Open isolated preview'}</button>{preview&&<iframe title="Isolated generated webapp" sandbox={report.execution_mode==='starter'?'allow-scripts':''} referrerPolicy="no-referrer" srcDoc={`<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data:; connect-src 'none'; form-action 'none'; base-uri 'none'; frame-src 'none'; worker-src 'none'">${artifact.content}`} className="h-[480px] w-full rounded border border-line2 bg-panel"/>}<details><summary className="text-xs text-dim">Inspect HTML source (generated code is untrusted)</summary><pre className="mt-2 max-h-80 overflow-auto whitespace-pre-wrap bg-panel p-4 text-xs">{artifact.content}</pre></details></>:<pre className="max-h-[480px] overflow-auto whitespace-pre-wrap border border-line bg-panel p-4 text-sm leading-6">{artifact.content}</pre>}</section>}
   <section><h2 className="label mb-3">Mission timeline · runtime source of truth</h2><ol className="max-h-72 overflow-auto space-y-2 text-xs">{result.record.timeline.map((event,i)=><li key={i} className="flex gap-3 border-b border-line pb-2"><Mono className="text-dim">{i+1}</Mono><span>{event.event_type}<span className="ml-2 text-dim">{event.timestamp}</span></span></li>)}</ol></section>
   <p className="text-xs leading-5 text-dim">{report.limitations.join(' ')}</p>
  </>}
 </div>;
}
