import test from "node:test";
import assert from "node:assert/strict";
import { Web3Grant, Web3Policy } from "../packages/contracts/src";
import { createIntent, intentDigest, evaluatePolicy, approveIntent, verifyApproval, assertWriteUnavailable, READ_FIRST_POLICY } from "../packages/web3/src";
const scope={organization_id:"org",project_id:"project",mission_id:"mission"};const now=new Date("2026-09-30T00:00:00.000Z");
function setup(){const intent=createIntent({intentId:"i",agentId:"agent",chain:{id:"solana",network:"devnet"},action:"transfer",sourceEntity:"from",targetEntity:"to",asset:"SOL",amount:"10",parameters:{program:"p"},reason:"test",riskLevel:"LOW",createdAt:now.toISOString()},scope);intent.simulationResult={success:true,intentDigest:intentDigest(intent)};
 const policy:Web3Policy={allowedChains:["solana"],allowedTokens:["SOL"],allowedPrograms:["p"],walletAllowlist:["from","to"],walletDenylist:[],maxAmountByAsset:{SOL:"20"},humanApprovalRequired:true,simulationRequired:true,blockHighRisk:true,maxTransactionsPerMinute:1};const grant:Web3Grant={...scope,agentIds:["agent"],permissions:["web3.execute"]};return{intent,policy,grant};}
test("all policy rules fail closed independently and default READ policy denies writes",()=>{const{intent,policy,grant}=setup();assert.equal(evaluatePolicy(intent,policy,grant,0,now).allowed,true);for(const patch of [{allowedChains:[]},{allowedTokens:[]},{allowedPrograms:[]},{walletAllowlist:[]},{walletDenylist:["from"]},{maxAmountByAsset:{SOL:"9"}},{maxTransactionsPerMinute:0}])assert.equal(evaluatePolicy(intent,{...policy,...patch},grant,0,now).allowed,false);for(const patch of [{riskLevel:"HIGH" as const},{riskLevel:"UNKNOWN" as const},{requiresApproval:false},{simulationResult:null},{status:"CONFIRMED" as const}])assert.equal(evaluatePolicy({...intent,...patch},policy,grant,0,now).allowed,false);assert.equal(evaluatePolicy(intent,policy,{...grant,mission_id:"foreign"},0,now).allowed,false);assert.equal(evaluatePolicy(intent,policy,{...grant,permissions:[]},0,now).allowed,false);assert.equal(evaluatePolicy(intent,policy,grant,1,now).allowed,false);assert.equal(evaluatePolicy(intent,READ_FIRST_POLICY,grant,0,now).allowed,false);});
test("approval is pinned to intent, policy and expiry; approval never enables V0.1 writes",()=>{const{intent,policy,grant}=setup();const result=evaluatePolicy(intent,policy,grant,0,now);const approval=approveIntent(intent,result,"human","2026-09-30T00:02:00.000Z",now);verifyApproval(intent,result,approval,now);assert.throws(()=>verifyApproval({...intent,amount:"11"},result,approval,now));assert.throws(()=>verifyApproval(intent,result,approval,new Date("2026-09-30T00:03:00.000Z")));assert.throws(()=>approveIntent(intent,{...result,allowed:false},"human",approval.expiresAt,now));assert.throws(()=>verifyApproval(intent,result,{...approval,approverId:"attacker"},now));assert.throws(()=>assertWriteUnavailable(),/UNSUPPORTED/);});
