import test from "node:test";
import assert from "node:assert/strict";
import { ChainAdapter } from "../packages/contracts/src";
import { SolanaAdapter, SolanaRPC, SPL_PROGRAMS, Web3Service, normalizeSolanaObservation } from "../packages/web3/src";
const address="11111111111111111111111111111111";const signature="1".repeat(64);const scope={organization_id:"org",project_id:"project",mission_id:"mission"};
function rpc(results:Record<string,unknown>,calls:string[]=[]):SolanaRPC{return new SolanaRPC("https://rpc.example",async(_url,init)=>{const request=JSON.parse(String(init?.body));calls.push(request.method);return Response.json({jsonrpc:"2.0",id:request.id,result:request.method==="getGenesisHash"?address:results[request.method]});});}
export function readAdapter():SolanaAdapter{return new SolanaAdapter(rpc({getBalance:{context:{slot:42},value:123},getAccountInfo:{context:{slot:42},value:{owner:address,executable:false,lamports:123}},getSlot:42}));}
test("ChainAdapter implements real read RPC contracts for wallet, balance, slot and block",async()=>{const adapter:ChainAdapter=new SolanaAdapter(rpc({getAccountInfo:{context:{slot:42},value:{owner:address,executable:false,lamports:123}},getBalance:{context:{slot:42},value:123},getSlot:42,getBlock:{blockhash:address,previousBlockhash:address,parentSlot:41,blockHeight:42}}));assert.equal((await adapter.connect()).id,"solana");assert.equal((await adapter.getWallet(address)).assurance,"RPC_VALIDATED");assert.equal((await adapter.getBalance(address)).cryptographicProof,false);assert.deepEqual((await adapter.getBalance(address)).value,{address,lamports:"123",decimals:9,asset:"SOL"});assert.equal((await adapter.getSlot()).value,42);assert.equal((await adapter.getBlock(42)).slot,42);await assert.rejects(adapter.submitTransaction({} as never,{} as never),/UNSUPPORTED/);await assert.rejects(adapter.simulateTransaction({} as never),/UNSUPPORTED/);await assert.rejects(adapter.buildTransaction({} as never),/UNSUPPORTED/);});
test("SPL and Token-2022 reads validate token owner/program and preserve arbitrary integer amounts",async()=>{let n=0;const adapter=new SolanaAdapter(new SolanaRPC("https://rpc.example",async(_url,init)=>{const r=JSON.parse(String(init?.body));if(r.method==="getGenesisHash")return Response.json({jsonrpc:"2.0",id:r.id,result:address});const program=SPL_PROGRAMS[n++];return Response.json({jsonrpc:"2.0",id:r.id,result:{context:{slot:42},value:[{pubkey:address,account:{owner:program,data:{parsed:{type:"account",info:{mint:address,owner:address,tokenAmount:{amount:"18446744073709551615",decimals:9}}}}}}]}});}));const result=await adapter.getTokenBalances(address);assert.equal((result.value as any).balances.length,2);assert.equal((result.value as any).balances[0].amount,"18446744073709551615");});
function transaction(error:unknown=null){return{slot:42,transaction:{signatures:[signature],message:{instructions:[{programId:address,parsed:{type:"transfer",info:{source:address,destination:address,lamports:1}}}]}},meta:{err:error,fee:5000}};}
test("successful finalized transaction normalizes events; failed transaction never verifies or emits successful transfer",async()=>{const status={context:{slot:42},value:[{slot:42,err:null,confirmationStatus:"finalized"}]};const adapter=new SolanaAdapter(rpc({getTransaction:transaction(),getSignatureStatuses:status}));assert.equal((await adapter.verifyTransaction(signature)).cryptographicProof,false);const world=normalizeSolanaObservation(await adapter.getTransaction(signature),scope);assert.ok(world.events.some(e=>e.eventType==="TOKEN_TRANSFERRED"));const failed=new SolanaAdapter(rpc({getTransaction:transaction({InstructionError:[0,"Custom"]}),getSignatureStatuses:{context:{slot:42},value:[{slot:42,err:{InstructionError:[0,"Custom"]},confirmationStatus:"finalized"}]}}));await assert.rejects(failed.verifyTransaction(signature));const events=normalizeSolanaObservation(await failed.getTransaction(signature),scope).events;assert.equal(events.length,1);assert.equal(events[0].eventType,"TRANSACTION_FAILED");});
test("bounded watch has cursor, cancellation, normalized observations and no hidden background timer",async()=>{const a=new SolanaAdapter(rpc({getSignaturesForAddress:[{signature,slot:42}],getTransaction:transaction()}));let count=0;for await(const observation of a.watchAddress(address,{limit:1})){count++;assert.ok(normalizeSolanaObservation(observation,scope).events.length);}assert.equal(count,1);for await(const observation of a.watchProgram(address,{limit:1,cursor:signature}))assert.equal(observation.method,"getSignaturesForAddress");const ctl=new AbortController();ctl.abort();await assert.rejects(a.getEvents(address,{limit:1,signal:ctl.signal}));await assert.rejects(a.getEvents(address,{limit:11}));});
test("unsupported chains, malformed RPC, unsafe numbers and transport failures are refused without leaking endpoints",async()=>{const service=new Web3Service(readAdapter());await assert.rejects(service.observe(scope,{chain:"ethereum",operation:"balance",address}),/CHAIN_UNSUPPORTED/);for(const body of [{jsonrpc:"2.0",id:999,result:1},{jsonrpc:"1.0",id:1,result:1},{jsonrpc:"2.0",id:1,error:{message:"privateKey"}}]){const r=new SolanaRPC("https://rpc.example",async()=>Response.json(body));await assert.rejects(r.request("getSlot"));}await assert.rejects(new SolanaRPC("https://rpc.example?key=secret",async()=>{throw Error("secret endpoint");}).request("getSlot"),e=>String(e)==="Web3Error: SOLANA_RPC_TRANSPORT_FAILED");assert.throws(()=>new SolanaRPC("http://localhost"));await assert.rejects(readAdapter().getBalance("bad"));await assert.rejects(new SolanaRPC("https://rpc.example").request("sendTransaction" as never),/METHOD_DENIED/);});

test("lossless RPC amounts preserve u64 and reject unsafe slots or malformed transfer operands",async()=>{const adapter=new SolanaAdapter(new SolanaRPC("https://rpc.example",async(_url,init)=>{const r=JSON.parse(String(init?.body));return new Response(r.method==="getGenesisHash"?JSON.stringify({jsonrpc:"2.0",id:r.id,result:address}):'{"jsonrpc":"2.0","id":'+r.id+',"result":{"context":{"slot":42},"value":18446744073709551615}}');}));assert.equal((await adapter.getBalance(address)).value && ((await adapter.getBalance(address)).value as any).lamports,"18446744073709551615");await assert.rejects(new SolanaAdapter(rpc({getSlot:9007199254740992})).getSlot());const bad=transaction();bad.transaction.message.instructions[0].parsed.info.source="invalid";await assert.rejects(new SolanaAdapter(rpc({getTransaction:bad})).getTransaction(signature));});
