import test from "node:test";
import assert from "node:assert/strict";
import { SolanaAdapter, SolanaRPC, Web3Service, installWeb3Executors, web3ReadTeam, web3ReadMission, projectEvidence } from "../packages/web3/src";
import { ExecutorRegistry, MissionKernel, MemoryMissionStore, FileMissionStore } from "../packages/runtime/src";
import { CapabilityCatalog } from "../packages/capabilities/src";
import { verifyCompletedMission } from "../packages/proof-core/src";
import { mkdtemp,rm } from "node:fs/promises";import { tmpdir } from "node:os";import { join } from "node:path";
const address="11111111111111111111111111111111";
function setup(){let calls=0;const service=new Web3Service(new SolanaAdapter(new SolanaRPC("https://rpc.example",async(_url,init)=>{calls++;const r=JSON.parse(String(init?.body));return Response.json({jsonrpc:"2.0",id:r.id,result:r.method==="getGenesisHash"?address:{context:{slot:42},value:1}});})));const registry=new ExecutorRegistry();const catalog=new CapabilityCatalog();installWeb3Executors(registry,catalog,service);const team=web3ReadTeam("org_dev_local","project_web3_local");const mission=web3ReadMission("web3_runtime",team,{chain:"solana",operation:"balance",address});return{service,registry,catalog,team,mission,calls:()=>calls};}
test("real OSA multi-agent path creates sealed Mission proof and replayable evidence-linked World; repeat is idempotent",async()=>{const s=setup();const store=new MemoryMissionStore();const kernel=new MissionKernel(store);await kernel.create(s.mission,s.team);s.service.authorize(s.mission,s.team);const run=await kernel.execute(s.mission.mission_id,s.registry);assert.equal(run.verdict,"VERIFIED");assert.equal(run.events.filter(e=>e.type==="AGENT_COMPLETED").length,4);const record=(await kernel.get(s.mission.mission_id))!;verifyCompletedMission(record);const world=projectEvidence(run.evidence,s.mission);assert.ok(world.entities.some(e=>e.type==="Wallet"));assert.ok(world.entities.every(e=>e.proofRefs.length));assert.deepEqual(projectEvidence(run.evidence,s.mission),world);const count=s.calls();assert.deepEqual(await kernel.execute(s.mission.mission_id,s.registry),run);assert.equal(s.calls(),count);assert.equal(s.catalog.list().find(c=>c.capability_id==="web3.execute")?.health,"UNAVAILABLE");const forged=structuredClone(run.evidence);forged[0].data.validated=false;assert.throws(()=>projectEvidence(forged,s.mission));assert.throws(()=>projectEvidence(run.evidence,{...s.mission,organization_id:"foreign"}));});
test("direct registry use cannot bypass scoped grants or policy; no RPC before denied permission",async()=>{const s=setup();const c={run_id:"r",execution_id:"e",operation_id:"o",mission:s.mission,agent:s.team.agents[0],input:s.mission.input};await assert.rejects(Promise.resolve().then(()=>s.registry.get("web3.monitor.v1")(c)),/PERMISSION_DENIED/);assert.equal(s.calls(),0);s.service.authorize(s.mission,s.team);await assert.rejects(Promise.resolve().then(()=>s.registry.get("web3.monitor.v1")({...c,mission:{...s.mission,organization_id:"foreign"}})),/PERMISSION_DENIED/);await assert.rejects(Promise.resolve().then(()=>s.registry.get("web3.execute.v1")(c)),/UNSUPPORTED/);assert.equal(s.calls(),0);});
test("evidence survives local FileMissionStore and replay through a fresh kernel",async()=>{const dir=await mkdtemp(join(tmpdir(),"osa-web3-"));try{const s=setup();const kernel=new MissionKernel(new FileMissionStore(dir));await kernel.create(s.mission,s.team);s.service.authorize(s.mission,s.team);const run=await kernel.execute(s.mission.mission_id,s.registry);const restored=(await new MissionKernel(new FileMissionStore(dir)).get(s.mission.mission_id))!;verifyCompletedMission(restored);assert.deepEqual(projectEvidence(restored.run!.evidence,s.mission),projectEvidence(run.evidence,s.mission));}finally{await rm(dir,{recursive:true,force:true});}});
