import test from "node:test";
import assert from "node:assert/strict";
import { ApiState,createApiServer } from "../apps/api/src";
import { createDevFixtureRegistry } from "../apps/api/src/server";
import { SolanaAdapter,SolanaRPC,Web3Service } from "../packages/web3/src";
import { AddressInfo } from "node:net";
async function server(fn:(base:string,state:ApiState)=>Promise<void>,configured=true,auth:"open"|"session"="open"){const service=new Web3Service(configured?new SolanaAdapter(new SolanaRPC("https://rpc.example",async(_url,init)=>{const r=JSON.parse(String(init?.body));return Response.json({jsonrpc:"2.0",id:r.id,result:r.method==="getGenesisHash"?"11111111111111111111111111111111":{context:{slot:42},value:12}});})):undefined);const state=new ApiState(undefined,undefined,undefined,auth,undefined,undefined,service);const s=createApiServer(createDevFixtureRegistry(),state);await new Promise<void>(resolve=>s.listen(0,"127.0.0.1",resolve));try{await fn(`http://127.0.0.1:${(s.address() as AddressInfo).port}`,state);}finally{await new Promise<void>((resolve,reject)=>s.close(e=>e?reject(e):resolve()));}}
const body={mission_id:"web3_api",input:{chain:"solana",operation:"balance",address:"11111111111111111111111111111111"}};
test("Web3 API executes existing Mission path, exposes proof-linked state and refuses writes and secret input",async()=>server(async base=>{const status=await(await fetch(`${base}/web3/status`)).json() as any;assert.equal(status.signingEnabled,false);const res=await fetch(`${base}/web3/observe`,{method:"POST",body:JSON.stringify(body)});const result=await res.json() as any;assert.equal(res.status,200,JSON.stringify(result));assert.equal(result.state,"COMPLETED");const saved=await(await fetch(`${base}/web3/missions/web3_api`)).json() as any;assert.equal(saved.record.run.verdict,"VERIFIED");assert.ok(saved.world.entities.length);const repeated=await(await fetch(`${base}/web3/observe`,{method:"POST",body:JSON.stringify(body)})).json() as any;assert.equal(repeated.run.execution_id,result.run.execution_id);for(const route of ["execute","approval","sign"]){assert.equal((await fetch(`${base}/web3/${route}`,{method:"POST",body:"{}"})).status,409);}assert.equal((await fetch(`${base}/web3/observe`,{method:"POST",body:JSON.stringify({...body,input:{...body.input,seedPhrase:"forbidden"}})})).status,400);assert.equal((await fetch(`${base}/web3/observe`,{method:"POST",body:JSON.stringify({...body,organization_id:"foreign"})})).status,403);assert.equal((await fetch(`${base}/web3/observe`,{method:"POST",body:JSON.stringify({...body,project_id:"foreign"})})).status,403);}));
test("unconfigured RPC reports unavailable and session routes refuse anonymous access",async()=>{await server(async base=>{const status=await(await fetch(`${base}/web3/status`)).json() as any;assert.equal(status.rpcConfigured,false);assert.ok(status.capabilities.every((c:any)=>c.health==="UNAVAILABLE"));assert.equal((await fetch(`${base}/web3/observe`,{method:"POST",body:JSON.stringify(body)})).status,503);},false);await server(async base=>{assert.equal((await fetch(`${base}/web3/status`)).status,401);},true,"session");});

test("Web3 evidence cannot leak through generic missions or runs routes to a foreign organization",async()=>server(async(base,state)=>{
 const res=await(await fetch(`${base}/web3/observe`,{method:"POST",body:JSON.stringify(body)})).json() as any;
 const session=state.sessions.create({identity_id:"foreign",provider:"local-dev",subject:"foreign",display_name:"Foreign",organization_id:"org_foreign",roles:["developer"],verified:true});
 for(const route of [`/web3/missions/${body.mission_id}`,`/missions/${body.mission_id}`,`/missions/${body.mission_id}/receipt`,`/runs/${res.run.run_id}`,`/runs/${res.run.run_id}/evidence`])assert.equal((await fetch(base+route,{headers:{authorization:`Bearer ${session.token}`}})).status,403,route);
}));
test("intent preview reports policy denial without persisting or executing client-supplied approvals",async()=>server(async base=>{
 const intent={intentId:"intent",agentId:"agent",chain:{id:"solana",network:"devnet"},action:"transfer",sourceEntity:"from",targetEntity:"to",asset:"SOL",amount:"1",parameters:{program:"program"},reason:"preview",riskLevel:"LOW",requiresApproval:false,status:"APPROVED",createdAt:"2026-09-30T00:00:00.000Z"};
 const response=await fetch(`${base}/web3/intents/preview`,{method:"POST",body:JSON.stringify({mission_id:"preview",intent})});const result=await response.json() as any;assert.equal(response.status,200);assert.equal(result.intent.status,"CREATED");assert.equal(result.policy.allowed,false);assert.equal(result.executed,false);assert.equal(result.persistence,"NOT_SAVED_PREVIEW");
}));
